---
- name: install pip packages
  hosts: raspiserver
  gather_facts: True
  sudo: true
  tasks:
    - name: Install global python requirements
      pip: name={{item}} state=present
      with_items:
        - unidecode

    - name: Pull sources from the repository.
      git: repo=https://github.com/lthiery/SPI-Py.git dest=/tmp/SPI-Py

    - name: chained shell command
      shell: "sudo python setup.py install"
      args:
        chdir: /tmp/SPI-Py